const Teleport = require("../../src");

module.exports = new Teleport("", {
    accessToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJpZCI6ImM0NjQ0NzMzLWRlZWEtNDdkOC1iMzVhLTg2ZjMwZmY5NjE4ZSIsInR5cGUiOiJ1c2VyIiwiSldUX3R5cGUiOiJVU0VSIiwiZW1haWwiOiJhbnRob255YnVkZEBpZGVlYS5jby51ayIsImZpcnN0X25hbWUiOiJBbnRob255IiwibGFzdF9uYW1lIjoiQnVkZCIsImRpc3BsYXlfbmFtZSI6IkFudGhvbnkgQnVkZCIsInByb2ZpbGVfaW1hZ2UiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL3YxL3VzZXIvcHJvZmlsZS1pbWFnZS9hbnRob255JTIwYnVkZCIsInNvdXJjZSI6InNlZWRlZCIsImdyb3VwX2lkIjoiMDAwMDAwMDAtOWEzNC00NDY2LWJhNGMtNDY0MzhkZWY3ZDdmIiwiaWF0IjoxNTk1NzgxNjE1LCJleHAiOjMyMjMwOTkyMzB9.kQbuXQ-fBNeRVUSt4qGapFew0q68Ig_eQRLCOXKgnpS-eRi4EqdRp1WKHlzFsaoEhjn1kxgpDcAMB6ZF5cFsTwVFXUP-fJzPaUGQhaHcdZjanTCn6jNjRch4BBVPvnWF_3TYSH2LjQKYtQQ1NlZhZ0_EookxNgbgMYmpQPKOCF-ixtzU1KhfIFjUFtv-Qrm2T0Nrzah6VHT4QW34FRIQF5DqTzJwHtYgAzeasqY0yFNeG6rp5ORMN7oHPxXbEJeLgEioZidbBkJyWcC7JrskV6MW3FVfd7xwNDZDkJyKQ8aZZ4Zjzyw8ev7HpzgfFE43IzBgHmHTrL09IAyllkSajw",
    hostname: "http://teleport.ideea.local/api/v1"
});
